sudo: required

language: go
go:
  - 1.5

services:
    - docker
install:
  - go get github.com/InteractiveLecture/id-extractor
  - go get github.com/InteractiveLecture/middlewares/jwtware
  - go get github.com/richterrettich/jsonpatch
  - go get github.com/InteractiveLecture/pgmapper
  - go get github.com/gorilla/mux
  - go get github.com/ant0ine/go-urlrouter

script:
  - ./build.sh
